Message  ::=  ( Sync | SyncAck | Reset | Subscribe |
    Nack | Rate | Ack | 
    ( ( ClientData | RelayData)  (NamedDataChunk ( EncDataBlock | DataBlock ) data )+ ) ) Header

Sync ::= tagSync  cookie origin senderID
    clientTime supportedFeatureVec

SyncAck ::= tagSyncAck  serverTime useFeatureVec

Reset ::= tagReset

Reset ::= tagResetRedirect  cookie originLen orginStringBytes port

Reset ::= tagResetRetry  cookie

Ack ::= tagAck clientSeqNum recvTime ackVec ecnVec

Rate ::= tagRate   bitRate

Nack ::= tagNack   relaySeqNum

Subscribe ::= tagSubscribe  ShortName

ClientData ::=  tagClientData clientSeqNum 

RelayData ::=  tagRelayData relaySeqNum relaySendTime

NamedDataChunk ::= ShortName lifeTime 

ShortName ::= tagShortName resourceID senderID sourceID mediaTime fragmentID

EncDataBlock ::=  tagEncDataBlock authTagLen metaDataLen cipherDataLen 

DataBlock ::= tagDataBlock metaDataLen dataLen 

Header ::=  pathToken ( tagHeaderSyn | tagPacketTypSynAck
        | tagHeaderRst |  tagHeaderData
        | tagHeaderSynCrazy | tagPacketTypSynAckCrazy
        | tagHeaderResCrazy | tagHeaderDataCrazy  )

clientSeqNum::= UInt32
relaySeqNum ::= UInt32
lifeTime ::=  varInt
bitRate ::= varInt
senderID ::= varInt
clientTime ::= varInt
versionVec1 ::= varInt
cookie::= varInt
originLen::= varInt
port ::= varInt
senderID::= varInt
clientTime::= varInt
supportedFeatureVec::= varInt
serverTime::= varInt
userFeatureVec::= varInt
recvTime::= varInt
ackVec::= varInt
encVec::= varInt
bitRate::= varInt
dataANdTagTotalLen ::= varInt
authTagLen::= varInt
dataLen::= varInt

originStringBytes ::= byte+
ciperTextAndTagBytes ::= bytes+
dataBytes ::= bytes+

varInt ::= Int7 | Int14 | Int29 | Int60
